### ISSUE TITLE
How to use with node <13.2

### ISSUE THREAD

**Issue by ziaulrehman40** [vanillaes/csv-es#10]
Readme mentions `A CommonJS bundle is included for backward compatible with node <= 13.2` but package does not even install on node <13.2 yarn add gives error of node version.

So how are we supposed to use this package on node < 13.2

Thanks.

**Comment by evanplaice** [comment]
For yarn, have you tried using the [--ignore-engies](https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-ignore-engines) option.

I'll add some code samples to the README.md. In short, it works just like CSV.parse/stringify work just like JSON.parse/stringify. Parse takes a string and turns it into an 2D array, stringify takes a 2D array and transforms it into a CSV.

**Comment by evanplaice** [comment]
Also, this lib is very much experimental. At some point within the next 6 weeks Node will publish a new release.

Included in that release is a new feature called 'conditional exports'. After it lands I'll be able to set pkg.main to the CommonJS build and you'll no longer need to deep import the package. You'll be able to.impprt the package with...

```javascript
const csv = require('csv-es');
```

**Comment by ziaulrehman40** [comment]
Thanks for the update in readme, but it troubles me that you said it is experimental, I am going to use this in production. Being on version 1.0.13 gives impression of it being stable.

So please clearly mention the state of the project in the readme if it is experimental, and in what ways or for what reasons it is not yet production ready/stable.

Thanks again for the library and the update.

**Comment by evanplaice** [comment]
Node's ES module support is the experimental part. Every package in this org is built on ES modules.

As for this project. It uses a new/improved version of the parser algorithm used in jquery-csv, which has well over half a million downloads.

The core API and features *are* stable and well tested. This package is also an early post 1.0 so there may be a few rough edges.

**Comment by ziaulrehman40** [comment]
Whatever experimental features it uses, mentioning them in the readme, along with their drawbacks would be nice i think. (if it does not already)
